Taka
TakayasuNasu/auth-sample pull request #12
Opened 2021-05-26 06:13 UTC by cookie777

- id -> course_id
- created component for parameters
- delete time stamp

2021-05-26 23:31 UTC, DaiSugi01 requested changes

2021-05-26 23:31 UTC, DaiSugi01 commented on docs/sample.yml
> +                $ref: "#/components/schemas/Status"
get rid of user_id

2021-05-27 01:21 UTC, cookie777 commented
I modified document

2021-05-28 00:04 UTC, DaiSugi01 approved these changes

2021-05-28 00:48 UTC, merged